name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Notetrix/notetrix/Notetrix.Web/Notetrix.Web.csproj
    - name: Build
      run: dotnet build --no-restore Notetrix/notetrix/Notetrix.Web/Notetrix.Web.csproj
